### ISSUE TITLE
Build failed on Ubunto 20.04, Noetic

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/ExplORB-SLAM#1] opened 2022-12-12 16:07 UTC
Hi,
I getting the following error. 

› cd ExplORB-SLAM-main                    ASLAM_Papers_With_Code/ExplORB-SLAM
λ › ls                                           ExplORB-SLAM/ExplORB-SLAM-main
2022_ROBOT_ExplORBSLAM_springer.pdf  build  devel  logs  src
λ › cd devel                                     ExplORB-SLAM/ExplORB-SLAM-main
λ › source setup.zsh                                    ExplORB-SLAM-main/devel
λ › pwd                                                 ExplORB-SLAM-main/devel
/home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/devel
λ › cd ..                                               ExplORB-SLAM-main/devel
λ › ls                                           ExplORB-SLAM/ExplORB-SLAM-main
2022_ROBOT_ExplORBSLAM_springer.pdf  build  devel  logs  src
λ › catkin b                                     ExplORB-SLAM/ExplORB-SLAM-main
==> Expanding alias 'b' from 'catkin b' to 'catkin build'
--------------------------------------------------------------------------------
Profile:                     default
Extending:          [cached] /home/user/data/git/active_graph_slam/devel:/home/user/data/ros_ws/devel:/opt/ros/noetic
Workspace:                   /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main
--------------------------------------------------------------------------------
Build Space:        [exists] /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/build
Devel Space:        [exists] /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/devel
Install Space:      [unused] /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/install
Log Space:          [exists] /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/logs
Source Space:       [exists] /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
--------------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------------
[build] Found 5 packages in 0.0 seconds.                                       
[build] Package table is up to date.                                           
Starting  >>> kobuki_plugins                                                   
Starting  >>> orb_slam2_ros                                                    
Starting  >>> robot_description                                                
Finished  <<< robot_description                [ 0.1 seconds ]                 
Finished  <<< orb_slam2_ros                    [ 0.2 seconds ]                 
Starting  >>> decision_maker                                                   
Starting  >>> frontier_detector                                                
Finished  <<< kobuki_plugins                   [ 0.2 seconds ]                 
Finished  <<< frontier_detector                [ 0.2 seconds ]                 
_______________________________________________________________________________
Errors     << decision_maker:cmake /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/logs/decision_maker/build.cmake.001.log
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:305 (message):
  catkin_package() include dir 'include' does not exist relative to
  '/home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/src/decision_maker'
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  CMakeLists.txt:18 (catkin_package)

cd /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/build/decision_maker; catkin build --get-env decision_maker | catkin env -si  /usr/bin/cmake /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/src/decision_maker --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/devel/.private/decision_maker -DCMAKE_INSTALL_PREFIX=/home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM/ExplORB-SLAM-main/install; cd -

...............................................................................
Failed     << decision_maker:cmake             [ Exited with code 1 ]          
Failed    <<< decision_maker                   [ 0.6 seconds ]                 
[build] Summary: 4 of 5 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.9 seconds total.

**Comment by JulioPlaced** [comment] 2022-12-21 08:26
Hello, this issue was caused by git not uploading empty directories (decision_maker/include/decision_maker). I have solved it by editing the package's cmake.

Closing issue.

**Comment by JulioPlaced** [comment] 2022-12-21 08:26
Hello, this issue was caused by git not uploading empty directories (decision_maker/include/decision_maker). I have solved it by editing the package's cmake.

Closing issue.

**Closed as completed by JulioPlaced** 2022-12-21 08:26 UTC
